### PR TITLE
fix: Fixed Span nesting for `ReadWriteTransactionCallable` by using parent SpanContext instead of just parent Context

### LINKED ISSUE #1491: For transaction operations, OpenTelemetry Trace spans not exhibiting correct hierarchy - all operations must be nested under the Run method.
nested span issue for transactions
Thanks for stopping by to let us know something could be better!

### PR DESCRIPTION
**Pull request by jimit-j-shah**
- This fixes the hierarchy of Spans appearing in a transaction under a Run method.
- Tested using existing transaction test

Fixes googleapis/google-cloud-java#11991  ☕️

### CODE REVIEW

**Comment by jimit-j-shah** [comment]
Original nested span issue for transactions

Fixed nested span issue for transactions

File: google-cloud-datastore/src/main/java/com/google/cloud/datastore/DatastoreImpl.java [hunk 1]
```diff
@@ -135,26 +143,57 @@ void setPrevTransactionId(ByteString transactionId) {
       options = options.toBuilder().setReadWrite(readWrite).build();
     }
 
+    private io.opentelemetry.api.trace.Span startSpanInternal(
```
Comment (cindy-peng) [inline google-cloud-datastore/src/main/java/com/google/cloud/datastore/DatastoreImpl.java:146]: Nit: The functionality is a bit unclear to me from the name `startSpanInternal` itself. Could we add some comments or rename this function, e.g.`startSpanWithParentContext`?

File: google-cloud-datastore/src/main/java/com/google/cloud/datastore/DatastoreImpl.java [hunk 2]
```diff
@@ -165,42 +204,30 @@ public T call() throws DatastoreException {
 
   @Override
   public <T> T runInTransaction(final TransactionCallable<T> callable) {
-    com.google.cloud.datastore.telemetry.TraceUtil.Span span =
```
Comment (cindy-peng) [inline google-cloud-datastore/src/main/java/com/google/cloud/datastore/DatastoreImpl.java:168]: What is the reason that we remove startSpan here and at L221 (edited version) below?

File: google-cloud-datastore/src/main/java/com/google/cloud/datastore/DatastoreImpl.java [hunk 3]
```diff
@@ -687,7 +714,7 @@ com.google.datastore.v1.BeginTransactionResponse beginTransaction(
     com.google.cloud.datastore.telemetry.TraceUtil.Span span =
         otelTraceUtil.startSpan(
             com.google.cloud.datastore.telemetry.TraceUtil.SPAN_NAME_BEGIN_TRANSACTION,
-            otelTraceUtil.getCurrentContext());
+            otelTraceUtil.getCurrentSpanContext());
```
Comment (cindy-peng) [inline google-cloud-datastore/src/main/java/com/google/cloud/datastore/DatastoreImpl.java:717]: Do we need to pass the same `otelTraceUtil.getCurrentSpanContext()` to L689?

File: google-cloud-datastore/src/main/java/com/google/cloud/datastore/DatastoreImpl.java (hunk 1 above)
Comment (jimit-j-shah) [reply google-cloud-datastore/src/main/java/com/google/cloud/datastore/DatastoreImpl.java:146]: Good point. Renamed the function.

File: google-cloud-datastore/src/main/java/com/google/cloud/datastore/DatastoreImpl.java (hunk 2 above)
Comment (jimit-j-shah) [reply google-cloud-datastore/src/main/java/com/google/cloud/datastore/DatastoreImpl.java:168]: So for now, I've replaced the `TraceUtil.startSpan` with `io.opentelemetry.api.trace.SpanBuilder` - `TraceUtil.startSpan` is really a wrapper around `io.opentelemetry.api.trace.SpanBuilder`.
I need to debug why using `TraceUtil.startSpan` doesn't work as expected (it has probably something to do with how the parent context is stored and propagated via thread-local storage but I'm not sure). 

I don't think this issue is a blocker and I can debug this in the background as we make progress with rest of the tracing work.

File: google-cloud-datastore/src/main/java/com/google/cloud/datastore/DatastoreImpl.java (hunk 3 above)
Comment (jimit-j-shah) [reply google-cloud-datastore/src/main/java/com/google/cloud/datastore/DatastoreImpl.java:717]: Sorry, I didn't understand the comment.

**Review by cindy-peng — APPROVED** [review]
